export default   [
    {
        title: "1st",
        type: "Residential",
        address: "Bangolore, India",
        coverImg: "./images/1(Residential)/16.jpeg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/1(Residential)/3.jpeg", "./images/1(Residential)/4.jpeg", "./images/1(Residential)/5.jpeg", "./images/1(Residential)/6.jpeg", "./images/1(Residential)/7.jpeg", "./images/1(Residential)/8.jpeg", "./images/1(Residential)/9.jpeg", "./images/1(Residential)/10.jpeg","./images/1(Residential)/11.jpeg", "./images/1(Residential)/12.jpeg", "./images/1(Residential)/13.jpeg", "./images/1(Residential)/14.jpeg","./images/1(Residential)/15.jpeg", "./images/1(Residential)/16.jpeg", "./images/1(Residential)/17.jpeg"],
    },
    {
        title: "2nd",
        type: "Residential",
        address: "Bangolore, India",
        coverImg: "./images/2(Residential)/1.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/2(Residential)/HALL.jpeg", "./images/2(Residential)/1.jpg", "./images/2(Residential)/2.jpg", "./images/2(Residential)/3.jpg", "./images/2(Residential)/4.jpg", "./images/2(Residential)/5.jpg", "./images/2(Residential)/6.jpeg", "./images/2(Residential)/7.jpg", "./images/2(Residential)/8.jpeg", "./images/2(Residential)/9.jpg", "./images/2(Residential)/10.jpeg", "./images/2(Residential)/11.jpeg", "./images/2(Residential)/12.jpeg"],
    },
    {
        title: "MODERN VILLA",
        type: "Residential",
        address: "Bangolore, India",
        coverImg: "./images/kitchen.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/kitchen.jpg", "./images/bedroom2.jpg", "./images/living_area.jpg", "./images/dressing_area2.jpg"],
    },
    {
        title: "MODERN VILLA",
        type: "Residential",
        address: "Bangolore, India",
        coverImg: "./images/kitchen.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/kitchen.jpg", "./images/bedroom2.jpg", "./images/living_area.jpg", "./images/dressing_area2.jpg"],
    },
    {
        title: "MODERN VILLA",
        type: "Residential",
        address: "Bangolore, India",
        coverImg: "./images/kitchen.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/kitchen.jpg", "./images/bedroom2.jpg", "./images/living_area.jpg", "./images/dressing_area2.jpg"],
    },
    {
        title: "SUBWAY",
        type: "Commercial",
        address: "Kempgowda Airport, Bangalore",
        coverImg: "./images/1(commercial)/4.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/1(commercial)/1.jpg", "./images/1(commercial)/2.jpg", "./images/1(commercial)/3.jpg", "./images/1(commercial)/4.jpg", "./images/1(commercial)/5.jpg", "./images/1(commercial)/6.jpg", "./images/1(commercial)/7.jpg"],
    },
    {
        title: "BREA BAKERY",
        type: "Commercial",
        address: "Kempgowda Airport, Bangalore",
        coverImg: "./images/2-commercial/1.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/2-commercial/1.jpg", "./images/2-commercial/2.jpg", "./images/2-commercial/3.jpg", "./images/2-commercial/4.jpg", "./images/2-commercial/5.jpg"],
    },
    {
        title: "KONE OFFICE",
        type: "Commercial",
        address: "Bangolore, India",
        coverImg: "./images/4(Commercial)/1.jpeg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/4(Commercial)/1.jpeg", "./images/4(Commercial)/2.jpeg", "./images/4(Commercial)/3.jpeg"],
    },
    {
        title: "RESTAURANT",
        type: "Commercial",
        address: "Bangolore, India",
        coverImg: "./images/living_area.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/kitchen.jpg", "./images/bedroom2.jpg", "./images/living_area.jpg", "./images/dressing_area2.jpg"],
    },
]