export default   [
    {
        title: "Ajit Sahoo Residence",
        type: "Residential",
        address: "Mantri Courtyard, Bangalore",
        coverImg: "./images/ajit-sahoo-villa/1.png",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden. The villa is perfect for a family or a group of friends.",
        images: ["./images/ajit-sahoo-villa/1.png", "./images/ajit-sahoo-villa/2.png", "./images/ajit-sahoo-villa/4.png", "./images/ajit-sahoo-villa/5.png", "./images/ajit-sahoo-villa/6.png", "./images/ajit-sahoo-villa/7.png", "./images/ajit-sahoo-villa/8.png", "./images/ajit-sahoo-villa/9.png","./images/ajit-sahoo-villa/11.png", "./images/ajit-sahoo-villa/13.png", "./images/ajit-sahoo-villa/14.png", "./images/ajit-sahoo-villa/15.png","./images/ajit-sahoo-villa/16.png", "./images/ajit-sahoo-villa/18.png", "./images/ajit-sahoo-villa/19.png","./images/ajit-sahoo-villa/21.png","./images/ajit-sahoo-villa/23.png","./images/ajit-sahoo-villa/24.png","./images/ajit-sahoo-villa/26.png","./images/ajit-sahoo-villa/27.png","./images/ajit-sahoo-villa/29.png","./images/ajit-sahoo-villa/30.png","./images/ajit-sahoo-villa/32.png","./images/ajit-sahoo-villa/33.png","./images/ajit-sahoo-villa/34.png","./images/ajit-sahoo-villa/35.png","./images/ajit-sahoo-villa/36.png","./images/ajit-sahoo-villa/37.png","./images/ajit-sahoo-villa/38.png","./images/ajit-sahoo-villa/39.png","./images/ajit-sahoo-villa/41.png"],
    },
    {
        title: "2nd",
        type: "Residential",
        address: "Bangolore, India",
        coverImg: "./images/2(Residential)/1.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/2(Residential)/HALL.jpeg", "./images/2(Residential)/1.jpg", "./images/2(Residential)/2.jpg", "./images/2(Residential)/3.jpg", "./images/2(Residential)/4.jpg", "./images/2(Residential)/5.jpg", "./images/2(Residential)/6.jpeg", "./images/2(Residential)/7.jpg", "./images/2(Residential)/8.jpeg", "./images/2(Residential)/9.jpg", "./images/2(Residential)/10.jpeg", "./images/2(Residential)/11.jpeg", "./images/2(Residential)/12.jpeg"],
    },
    {
        title: "1st",
        type: "Residential",
        address: "Bangolore, India",
        coverImg: "./images/1(Residential)/16.jpeg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/1(Residential)/3.jpeg", "./images/1(Residential)/4.jpeg", "./images/1(Residential)/5.jpeg", "./images/1(Residential)/6.jpeg", "./images/1(Residential)/7.jpeg", "./images/1(Residential)/8.jpeg", "./images/1(Residential)/9.jpeg", "./images/1(Residential)/10.jpeg","./images/1(Residential)/11.jpeg", "./images/1(Residential)/12.jpeg", "./images/1(Residential)/13.jpeg", "./images/1(Residential)/14.jpeg","./images/1(Residential)/15.jpeg", "./images/1(Residential)/16.jpeg", "./images/1(Residential)/17.jpeg"],
    },
    {
        title: "3rd",
        type: "Residential",
        address: "Bangolore, India",
        coverImg: "./images/3(Residential)/1.jpeg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/3(Residential)/1.jpeg", "./images/3(Residential)/2.jpeg", "./images/3(Residential)/3.jpeg", "./images/3(Residential)/4.jpeg", "./images/3(Residential)/5.jpeg", "./images/3(Residential)/6.jpeg", "./images/3(Residential)/7.jpeg", "./images/3(Residential)/8.jpeg"],
    },
    {
        title: "4",
        type: "Residential",
        address: "Bangolore, India",
        coverImg: "./images/4(Residential)/1.jpeg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/4(Residential)/1.jpeg", "./images/4(Residential)/2.jpeg", "./images/4(Residential)/3.jpeg", "./images/4(Residential)/4.jpeg", "./images/4(Residential)/5.jpeg"],
    },
    {
        title: "5",
        type: "Residential",
        address: "Bangolore, India",
        coverImg: "./images/5(Residential)/1.JPG",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/5(Residential)/1.JPG", "./images/5(Residential)/2.JPG", "./images/5(Residential)/3.JPG", "./images/5(Residential)/4.JPG", "./images/5(Residential)/5.JPG", "./images/5(Residential)/6.JPG", "./images/5(Residential)/7.JPG", "./images/5(Residential)/8.JPG","./images/5(Residential)/9.JPG", "./images/5(Residential)/10.JPG", "./images/5(Residential)/11.JPG", "./images/5(Residential)/12.JPG","./images/5(Residential)/13.JPG", "./images/5(Residential)/14.JPG", "./images/5(Residential)/15.JPG","./images/5(Residential)/16.JPG","./images/5(Residential)/17.JPG","./images/5(Residential)/18.JPG"],
    },
    {
        title: "6",
        type: "Residential",
        address: "Bangolore, India",
        coverImg: "./images/6(Residential)/1.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/6(Residential)/1.jpg", "./images/6(Residential)/2.jpg", "./images/6(Residential)/3.jpg", "./images/6(Residential)/4.jpg", "./images/6(Residential)/5.jpg", "./images/6(Residential)/6.jpg", "./images/6(Residential)/7.jpg", "./images/6(Residential)/8.jpg"],
    },
    {
        title: "Amar Kumar Residence",
        type: "Residential",
        address: "Risinia Skyon, Hyderabad",
        coverImg: "./images/7(Residential)/1.jpeg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/7(Residential)/1.jpeg", "./images/7(Residential)/2.jpeg", "./images/7(Residential)/3.jpeg", "./images/7(Residential)/4.jpeg", "./images/7(Residential)/5.jpeg", "./images/7(Residential)/6.jpeg", "./images/7(Residential)/7.jpeg"],
    },
    {
        title: "8",
        type: "Residential",
        address: "Bangolore, India",
        coverImg: "./images/8(Residential)/1.JPG",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/8(Residential)/1.JPG", "./images/8(Residential)/2.JPG", "./images/8(Residential)/3.JPG", "./images/8(Residential)/4.JPG", "./images/8(Residential)/5.JPG"],
    },
    {
        title: "SUBWAY",
        type: "Commercial",
        address: "Kempgowda Airport, Bangalore",
        coverImg: "./images/1(commercial)/4.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/1(commercial)/1.jpg", "./images/1(commercial)/2.jpg", "./images/1(commercial)/3.jpg", "./images/1(commercial)/4.jpg", "./images/1(commercial)/5.jpg", "./images/1(commercial)/6.jpg", "./images/1(commercial)/7.jpg"],
    },
    {
        title: "BREA BAKERY",
        type: "Commercial",
        address: "Kempgowda Airport, Bangalore",
        coverImg: "./images/2-commercial/1.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/2-commercial/1.jpg", "./images/2-commercial/2.jpg", "./images/2-commercial/3.jpg", "./images/2-commercial/4.jpg", "./images/2-commercial/5.jpg"],
    },
    {
        title: "KONE OFFICE",
        type: "Commercial",
        address: "Bangolore, India",
        coverImg: "./images/4(Commercial)/1.jpeg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/4(Commercial)/1.jpeg", "./images/4(Commercial)/2.jpeg", "./images/4(Commercial)/3.jpeg"],
    },
    {
        title: "OFFICE SPACE",
        type: "Commercial",
        address: "Bangolore, India",
        coverImg: "./images/3(Commercial)/4.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/3(Commercial)/1.jpg", "./images/3(Commercial)/2.jpg", "./images/3(Commercial)/4.jpg", "./images/3(Commercial)/5.jpg","./images/3(Commercial)/6.jpg","./images/3(Commercial)/7.jpg","./images/3(Commercial)/8.jpg","./images/3(Commercial)/9.jpg","./images/3(Commercial)/10.jpg","./images/3(Commercial)/11.jpg","./images/3(Commercial)/12.jpg","./images/3(Commercial)/13.jpg","./images/3(Commercial)/14.jpg","./images/3(Commercial)/15.jpg","./images/3(Commercial)/16.jpg","./images/3(Commercial)/17.jpg","./images/3(Commercial)/18.jpg","./images/3(Commercial)/19.jpg","./images/3(Commercial)/20.jpg","./images/3(Commercial)/21.jpg","./images/3(Commercial)/22.jpg","./images/3(Commercial)/23.jpg"],
    },
    {
        title: "LAYOUT DESIGN",
        type: "Commercial",
        address: "Bangolore, India",
        coverImg: "./images/5(Commercial)/AKME.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/4(Commercial)/AKME.jpg", "./images/4(Commercial)/Govindalaya.jpg", "./images/4(Commercial)/Organic-layout.jpg"],
    }
]