export default   [
    {
        title: "MODERN VILLA",
        type: "Residential",
        address: "Bangolore, India",
        coverImg: "./images/kitchen.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/kitchen.jpg", "./images/bedroom2.jpg", "./images/living_area.jpg", "./images/dressing_area2.jpg"],
    },
    {
        title: "MODERN VILLA",
        type: "Residential",
        address: "Bangolore, India",
        coverImg: "./images/kitchen.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/kitchen.jpg", "./images/bedroom2.jpg", "./images/living_area.jpg", "./images/dressing_area2.jpg"],
    },
    {
        title: "MODERN VILLA",
        type: "Residential",
        address: "Bangolore, India",
        coverImg: "./images/kitchen.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/kitchen.jpg", "./images/bedroom2.jpg", "./images/living_area.jpg", "./images/dressing_area2.jpg"],
    },
    {
        title: "MODERN VILLA",
        type: "Residential",
        address: "Bangolore, India",
        coverImg: "./images/kitchen.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/kitchen.jpg", "./images/bedroom2.jpg", "./images/living_area.jpg", "./images/dressing_area2.jpg"],
    },
    {
        title: "MODERN VILLA",
        type: "Residential",
        address: "Bangolore, India",
        coverImg: "./images/kitchen.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/kitchen.jpg", "./images/bedroom2.jpg", "./images/living_area.jpg", "./images/dressing_area2.jpg"],
    },
    {
        title: "CASIO STORE",
        type: "Commercial",
        address: "Bangolore, India",
        coverImg: "./images/living_area.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/kitchen.jpg", "./images/bedroom2.jpg", "./images/living_area.jpg", "./images/dressing_area2.jpg"],
    },
    {
        title: "BAKERY SHOP",
        type: "Commercial",
        address: "Bangolore, India",
        coverImg: "./images/living_area.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/kitchen.jpg", "./images/bedroom2.jpg", "./images/living_area.jpg", "./images/dressing_area2.jpg"],
    },
    {
        title: "CASIO STORE",
        type: "Commercial",
        address: "Bangolore, India",
        coverImg: "./images/living_area.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/kitchen.jpg", "./images/bedroom2.jpg", "./images/living_area.jpg", "./images/dressing_area2.jpg"],
    },
    {
        title: "RESTAURANT",
        type: "Commercial",
        address: "Bangolore, India",
        coverImg: "./images/living_area.jpg",
        description: "This modern villa is located in Bangolore, India. It has 4 bedrooms, 3 bathrooms, and a large kitchen. The villa is surrounded by a beautiful garden and a swimming pool. The villa is perfect for a family or a group of friends.",
        images: ["./images/kitchen.jpg", "./images/bedroom2.jpg", "./images/living_area.jpg", "./images/dressing_area2.jpg"],
    },
]